### ISSUE TITLE
Floor function

### ISSUE THREAD

**Issue by sohraa3** [hakaru-CS4ZP6/hakaru#17]
The transformation from standard uniform to benford requires a floor function. But I could not find any function in hakaru that would do that.

http://www.math.wm.edu/~leemis/chart/UDR/UDR.html

@JacquesCarette

**Comment by JacquesCarette** [comment]
If you add me to the project, then you could assign this issue to me.
I've asked the team about this.

**Comment by JacquesCarette** [comment]
I understand that this is blocking you for Benford - anything else? I am trying to figure out the relative priority.

**Comment by mkhattab940** [comment]
I think that's it. I haven't come across any other transformation that takes a floor

**Comment by JacquesCarette** [comment]
Ok, it's in my 'to do' list (at the appropriate priority).

**Comment by JacquesCarette** [comment]
I believe that commit https://github.com/hakaru-dev/hakaru/commit/62c662f2f9b52c817d54ed1c41dac4fe374daeec on master fixes this. You should merge this in.

Please close when you can verify it. In the meantime, I am switching assignees.

**Comment by mkhattab940** [comment]
I have pulled in the latest code to master. @sohraa3 try it out

**Comment by mkhattab940** [comment]
@sohraa3 Have you tried this yet?

**Comment by sohraa3** [comment]
I tried floor(). it gives me this error. 

hakaru: TODO: evaluatePrimOp{Floor}
CallStack (from HasCallStack):
  error, called at haskell/Language/Hakaru/Sample.hs:382:5 in hakaru-0.6.0-AbnzUW5EnqjBuQmLn3LJbU:Language.Hakaru.Sample

**Comment by JacquesCarette** [comment]
You did make sure to recompile hakaru first, right?

**Comment by sohraa3** [comment]
I did "git pull" and then "stack install"

**Comment by mkhattab940** [comment]
Were you working from the master branch when you tried this?

**Comment by mkhattab940** [comment]
To pull the latest master code into your working branch

git checkout master 
git pull
git checkout your-branch
git merge master

**Comment by mkhattab940** [comment]
Also try deleting `hakaru/.stack-work` and the contents of `~/.local/bin` before running `stack install`

**Comment by JacquesCarette** [comment]
`stack clean` should be enough...

**Comment by sohraa3** [comment]
I still get the same message.
My hakaru program is `floor(3.6)`
I ran these in order from the master branch:
`git pull`
`stack clean`
`stack install`

**Comment by JacquesCarette** [comment]
Ok, I've re-added this to my 'to do' list. Unlikely to get to it until next week though.

**Comment by JacquesCarette** [comment]
I did miss a case. Merge in c561495f from master.

**Comment by JacquesCarette** [comment]
[Note that you can re-open if it seems that it is not fully fixed]
