### ISSUE TITLE
Discrete functions with infinite categories

### ISSUE THREAD

**Issue by mkhattab940** [hakaru-CS4ZP6/hakaru#20]
http://www.math.wm.edu/~leemis/chart/UDR/PDFs/Logarithm.pdf
http://www.math.wm.edu/~leemis/chart/UDR/PDFs/Discreteweibull.pdf

A number of discrete functions like the above 2 have no upper bound on the value x can take. (The rest have further complications which we will deal with once this issue is solved)

Previously, we've been able to implement discrete distributions using the categorical function, and that's how I would begin to attack this problem, but we can't go feeding categorical() an infinite array.

Rather unsure how to proceed...

**Comment by mkhattab940** [comment]
@JacquesCarette I believe we discussed this in our last meeting. You said it would take some care. Can you point us in the right direction of how to go about this?

**Comment by JacquesCarette** [comment]
You need to use a weighted `Countable` to implement these. `Countable` is to `Nat` what `Lesbesgue` is to `Real`. So you put a `weight` in front of it, and voila!

**Comment by sohraa3** [comment]
@JacquesCarette I can't understand what Lesbesgue does. Also is there documentation on how to use Countable? I get an error saying the name is not in scope.

**Comment by JacquesCarette** [comment]
`Lebesgue` is essentially `uniform` on all of the real line.  It might be that `Countable` is actually called `Counting`...

**Comment by sohraa3** [comment]
@JacquesCarette So our problem was that, we couldn't pass an infinite array to categorical. I am not sure how counting can be used to overcome this problem. Can you give us some guidance on how to do this?

**Comment by JacquesCarette** [comment]
You don't want an infinite array, you want a *formula* which is used as a weight.   The documents you linked to has the formulas you need.

**Comment by sohraa3** [comment]
@JacquesCarette 
Is this the right way to do it? The first argument of weight() is the p.m.f formula found in the documents. The second argument of weight() is the absolute value of the counting variable to only account for positive integers.

def Discrete_Weibull(p prob, beta prob):
	x <~ counting
	weight(real2prob((real2prob(1-p) ** x) ** beta - (real2prob(1-p) ** (x+1)) ** beta) , return abs(x))

**Comment by JacquesCarette** [comment]
That sort-of works, but isn't really the best way to do it.

    def Discrete_Weibull(p prob, beta prob):
        x <~ counting
        weight( if (x<0) 0 (real2prob((real2prob(1-p) ** x) ** beta - (real2prob(1-p) ** (x+1)) ** beta)),
            return x)

is better. [I may have some syntax error in the `if`, but the idea should be clear].
