### ISSUE TITLE
Error Throwing

### ISSUE THREAD

**Issue by mkhattab940** [hakaru-CS4ZP6/hakaru#33]
Some distributions are defined in terms of parameters with limitations of their value (e.g. 0 < k < 1). Need a way to throw an error in case a language user calls the distribution with parameter values violating such restrictions.

**Comment by JacquesCarette** [comment]
Added to my list.

**Comment by JacquesCarette** [comment]
There seems to be no actual feature.

I think that what you can do, for now, is to have the distribution function return the 0 measure when the parameter is out of bounds.  i.e.

    reject. measure(real)

for example is the 0 measure over the reals.

**Comment by JacquesCarette** [comment]
I believe that is sufficient to close the issue?
