### ISSUE TITLE
Infinite sums in PDFs

### ISSUE THREAD

**Issue by sohraa3** [hakaru-CS4ZP6/hakaru#35]
http://www.math.wm.edu/~leemis/chart/UDR/UDR.html

Some of the distributionds from the above link have PDFs that include infinite sums. How could these be implemented in Hakaru?
Examples are: Power series, Zeta, Doubly noncentral F, Noncentral beta, Noncentral F, and, von Mises

**Comment by JacquesCarette** [comment]
`summate` can do infinite sums.  You can use the PDF as-is, certainly for noncentral beta, but I think for most of them.

**Comment by sohraa3** [comment]
@JacquesCarette 
I get the error bellow when I execute this code `(summate i from 1 to ∞: (1/i)**3)` . Is this the right way to do it?
`hakaru: Can not evaluate infinity for natural numbers
CallStack (from HasCallStack):
  error, called at haskell/Language/Hakaru/Sample.hs:339:27 in hakaru-0.6.0-AbnzUW5EnqjBuQmLn3LJbU:Language.Hakaru.Sample`

**Comment by JacquesCarette** [comment]
I do believe that that is the right way to do it. But you might not be able to ever `Sample` it.  But that's ok. Being able to represent them is already quite useful.

**Comment by JacquesCarette** [comment]
The main question is, does it work in `Simplify`?

**Comment by JacquesCarette** [comment]
Can you please create an explicit test (that fails) for this?  Or at the very least, check in a specific `.hk` file that shows the problem, and post the explicit way in which you call hakaru that causes the problem. The issue, as is, is too vague.

**Comment by sohraa3** [comment]
It does work with `hk-maple` command but not with `hakaru`. Is that enough or do you expect it to work with both?

**Comment by JacquesCarette** [comment]
That is enough!
