### ISSUE TITLE
Hakaru Paper Discussion

### ISSUE THREAD

**Issue by staplejw** [hakaru-CS4ZP6/hakaru#39]
We are beginning to tackle major sections of our paper. We have created this google doc for brainstorming ideas. https://docs.google.com/document/d/18redrh2HjrG1Y62bn7KhUCnyKR6yi7JZEwF85q0O3OQ/edit?usp=sharing

**Comment by JacquesCarette** [comment]
I can't access it. Can you add `jacques.carette@gmail.com` to the people who can see this?

**Comment by JacquesCarette** [comment]
BTW, issues are best assigned to at most 2 people (and even then).  Sometimes it makes sense to create a milestone which is composed of a bunch of issues; each issue is assigned a single 'owner'.

**Comment by staplejw** [comment]
@JacquesCarette I have given you access rights for this file. There is also a 'report.tex' in the making, which I will share once more content has been transferred over.

**Comment by JacquesCarette** [comment]
Ok, got it.

Do you just want me to generally comment on it, or did you have some specific questions?

**Comment by JacquesCarette** [comment]
@staplejw asking again: what are you expecting from me on this?

**Comment by staplejw** [comment]
Since nothing is exactly finalized at this point, general
comments/critiques would be great!

**Comment by staplejw** [comment]
Since nothing is exactly finalized at this point, general comments/critiques would be great!

**Comment by JacquesCarette** [comment]
The organization of the paper is good. The outlined material is good too. Though there is a danger that some of the pieces will get drowned or feel out of place in the 'finished' paper (i.e. the Sublime plug-in is the most obvious thing here).  Just make sure to keep this in mind as you evolve things.

You may find Google Docs to be a poor environment for writing about Hakaru -- the math will soon strain things quite severely.  LaTeX would actually be easier...

You should try to sample from some distributions (especially the new ones), and then do plots of histograms. Including some of the equivalent ones, to show 'visually' that they do seem related.  Of course, sampling is inexact, so histograms are 'impressionistic' and prove nothing!

**Comment by JacquesCarette** [comment]
Is this still a 'live' issue?

**Comment by staplejw** [comment]
Yes. With the poster now out of the way, the paper will become my main focus for the next week.

**Comment by JacquesCarette** [comment]
When you need me to look at things, make sure to explicitly ping me.

**Comment by staplejw** [comment]
Noted.
