### ISSUE TITLE
Infinite sequence as a parameter 

### ISSUE THREAD

**Issue by sohraa3** [hakaru-CS4ZP6/hakaru#40]
http://www.math.wm.edu/~leemis/chart/UDR/PDFs/Powerseries.pdf

It seems that the power series distribution takes an infinite sequence for one of its input parameters. I know you can't have infinite size arrays in hakaru but is there any other way of creating an infinite sequence?

**Comment by JacquesCarette** [comment]
Yes, you can use a function of type `Nat -> Prob` as the `a`. That is what an infinite sequence is.
