### ISSUE TITLE
Prob return types for chi distributions

### ISSUE THREAD

**Issue by mkhattab940** [hakaru-CS4ZP6/hakaru#43]
Hi @JacquesCarette 

Referring to the convo [here](https://github.com/hakaru-CS4ZP6/hakaru/issues/25) about making sure chiSq returns a prob, you said:

_"Yes, please make sure all of these return prob. There should be no need to cast, as it should be obvious that they are all positive."_

I'm unsure how to get any of the chi distributions to return prob values without a cast since these distributions are built up from the normal distribution (which returns real values) and their implementations use mathematical operators which results in a real when applied to reals/probs.

Is there some other way to ensure these distributions returns a prob type?

**Comment by JacquesCarette** [comment]
I need the exact details.  The PDF for chi-squared is 'obviously' positive.  And the relation to normal that I know is only asymptotic, not exact.

**Comment by mkhattab940** [comment]
Well, here is our implementation of chi-squared:

```
def chiSq_iid(n nat, mean real, stdev prob):
	q <~ plate _ of n: normal(mean,stdev)
	return summate i from 0 to size(q): 
		((q[i]-mean)/stdev)^2
```

As far as I can tell, even if normal wasn't returning reals, the term in the summate would be because of the subtraction before the division. Isn't the option to cast to prob then?

**Comment by JacquesCarette** [comment]
Yes.  The squaring does ensure the results are positive, so this is safe.

**Comment by mkhattab940** [comment]
Just to clarify, even though its output is strictly positive, it won't let me explicitly type it as prob without a real2prob. Shall I give them real return types, then?

**Comment by JacquesCarette** [comment]
No, use `real2prob`.
