### ISSUE TITLE
Distributions that can't be sampled from in stdlib

### ISSUE THREAD

**Issue by sohraa3** [hakaru-CS4ZP6/hakaru#45]
I was wondering if distributions that can't be sampled from should still be present in symbolic form in the stdlib. These are the ones that include infinite operations such as the power series distribution. They work with hk-maple and are useful for testing. My latest pull request includes some of these distributions that I put in a folder named symbolicDistributions under stdlib.

**Comment by JacquesCarette** [comment]
Yes.  It still represents forward progress.
