### ISSUE TITLE
Merged pull request not showing

### ISSUE THREAD

**Issue by sohraa3** [hakaru-CS4ZP6/hakaru#48]
Pull request #156 Erlang test1, #157 Erlang test2, #158 Erlang test3 were merged into hakaru-dev master but the corresponding changes do not appear. Test and expected files should be in tests/RoundTrip and there should be additions in RoundTrip.hs.

**Comment by JacquesCarette** [comment]
There were **massive** conflicts in these PRs as they seemed to all be independent but all changed the same files.  I tried to merge as best I could, and clearly did not succeed.

You know much better than I do what the final state should be -- please submit an additional PR that fixes my merge mistakes.
