### ISSUE TITLE
Inlining expected files to pass the 0-test, import feature and hk-maple

### ISSUE THREAD

**Issue by mkhattab940** [hakaru-CS4ZP6/hakaru#49]
As per https://github.com/hakaru-dev/hakaru/pull/154

The issues with failing the 0-test were solved by inlining everything. Most of the tests I've written related to the exponential distribution had the same issues and I solved them same way.

Ideally, we would have used an import feature to call distributions directly from stdlib to write these test case files. I'd expect the exact same issues to arise in this case, making import useless for writing expected files. Isn't this inability to automatically in-line a problem then?

Not an issue for our project, but something I wanted to bring up in case it hasn't been considered.

**Comment by JacquesCarette** [comment]
Writing expected test files is inherently a manual thing. You're testing that `Simplify` does all sorts of operations correctly, including inlining.  So you need to write the expected 'by hand'.  You can, of course, use some machine assistance in deriving things.
