### ISSUE TITLE
exponents with negative base

### ISSUE THREAD

**Issue by sohraa3** [hakaru-CS4ZP6/hakaru#50]
It seems that hakaru can not evaluate exponents with a negative base.
`(-1.0)**3` gives me `expected prob, found real`

**Comment by JacquesCarette** [comment]
This is badly documented.  `**` is 'real powering' for the function of type `prob -> real -> prob` while `^` is 'nat powering` of type `real -> nat -> real`.  You want the latter.

**Comment by sohraa3** [comment]
Is there a way to do real -> prob -> real ? That is what I need in my program. The code that I wrote in the first issue was an example.
