### ISSUE TITLE
doubly noncentral F

### ISSUE THREAD

**Issue by sohraa3** [hakaru-CS4ZP6/hakaru#52]
[http://www.math.wm.edu/~leemis/chart/UDR/PDFs/Doublynoncentralf.pdf](url)

The PDF of doubly noncentral F has a function in the denominator called B. I could not find the definition for it or an alternative version of the pdf since the resources on this distribution are very limited.

**Comment by JacquesCarette** [comment]
That would be the Beta function.  Represented as `betaFunc` in the external syntax.
